---
# Nginx configuration.   
- name: Set IP of Nginx server.
  shell: hostname -i
  register: ipoutput
- debug: var=ipoutput.stdout

- name: Assign IP to variable.
  set_fact:
    server_ip: "{{ ipoutput.stdout }}:{{ nginx_listen_port_ipv4_ssl }}"
  
- name: create folder if not exists.
  shell: mkdir {{ item }}
  with_items: 
    - "{{ nginx_sites_available_dir }}"
    - "{{ nginx_sites_enabled_dir }}"
  ignore_errors: true

- name: Copy configuration in place.
  template:
    src: "{{ lb_conf_template }}"
    dest: "{{ nginx_sites_available_dir }}/nginx.cfg"
    owner: root
    group: root
    mode: 0644
  notify: 
    - validate config
    - reload nginx

- name: Create symlink
  file:
    src: "{{ nginx_sites_available_dir }}/nginx.cfg"
    dest: "{{ nginx_sites_enabled_dir }}/default"
    state: link
  notify: 
    - validate config
    - reload nginx

