---
# Nginx configuration.   
- name: create folder if not exists.
  file:
    path: "{{ item }}"
    state: directory
  with_items: 
    - "{{ nginx_sites_available_dir }}"
    - "{{ nginx_sites_enabled_dir }}"
#  ignore_errors: true

- name: Copy configuration in place.
  template:
    src: "{{ lb_conf_template }}"
    dest: "{{ nginx_sites_available_dir }}/nginx.cfg"
    owner: root
    group: root
    mode: 0644
  notify: 
    - validate config
    - reload nginx

- name: Create symlink
  file:
    src: "{{ nginx_sites_available_dir }}/nginx.cfg"
    dest: "{{ nginx_sites_enabled_dir }}/default"
    state: link
  notify: 
    - validate config
    - reload nginx

