---
- name: Install apache to host website.
  package:
    name: httpd
    state: present
  changed_when: false
  notify: 
    - restart apache

- name: Check if dir exist or not.
  stat: 
    path: "{{ nginx_document_root }}"
  register: dir_result

- name: Create index.html file.
  file:
    path: "{{ nginx_document_root }}/index.html"
    state: touch
  when: dir_result is success

- name: Generate index.html
  template:
     src: index.j2
     dest: "{{ nginx_document_root }}/index.html"
     owner: root
     group: root
     mode: 0744
  notify: 
    - reload nginx