---
- name: Check if redhat appstream repo is already present.
  shell: cat /etc/yum.repos.d/redhat.repo | grep appstream-rpms -A5 | grep enabled
  register: result

- name: Create nginx.repo file.
  file:
    path: /etc/yum.repos.d/nginx.repo
    state: touch
  when: result.stdout.find('enabled') != 1

- name: Enable Nginx Repo
  template:
    src: "{{ nginx_repo_template }}"
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644
  when: result.stdout.find('enabled') != 1

- name: ensure Nginx package is installed.
  package:
    name: "{{ nginx_rpm }}"
    state: present

