---
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template_web }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - validate config
    - reload nginx