---
- name: Configuration of Nginx load balancer.
  hosts: all
  become: true
  vars_files:
    - var/nginx_vars.yml
  tasks:
    - name: Calling load balancer Role.
      include_role: 
        name: role_common

- name: Configuration of Nginx load balancer.
  hosts: load_balancer
  become: true
  vars_files:
    - var/nginx_vars.yml
  tasks:
    - name: Calling load balancer Role.
      include_role: 
        name: role_loadbalancer
        
- name: Configuration of Sites for backend servers.
  hosts: web_servers
  become: true
  vars_files:
    - var/nginx_vars.yml
  tasks:
    - name: Calling Website Role.
      include_role: 
        name: role_website
